kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: registry.lan/krichy/patroni-pg
    registry: registry.lan
    insecure: true
