kind: pipeline
name: default

platform:
  os: linux

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: rkojedzinszky/postgres-patroni
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
    auto_tag: true
