kind: pipeline
name: default

platform:
  os: linux

steps:
- name: generate tags
  image: alpine
  commands:
  - apk --no-cache add git
  - git fetch --tags
  - sh gen-tags.sh $${DRONE_STAGE_ARCH} > .tags

- name: docker
  image: plugins/docker
  settings:
    repo: rkojedzinszky/postgres-patroni
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
